### ISSUE TITLE
feat: 添加 stable diffusion API 支持

### ISSUE THREAD

**Issue by Well2333** [Alpaca4610/nonebot_plugin_nai3_bot#3]
ref: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API
stable diffusion webui 项目可以通过 webui 调用 API 进行自建的AI绘图，无需依赖于 novel ai API，对于一些拥有 GPU 服务器或其他可以本地运行的用户来说可以增添一种选择。
如果您认为这项改动可以被接受，本人可以近期完成这项改动并提交相关的 PR。

**Comment by Alpaca4610** [comment]
👌欢迎PR！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月8日(周六) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Alpaca4610/nonebot_plugin_nai3_bot] feat: 添加 stable diffusion API 支持 (Issue #3)




 
ref: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API
 stable diffusion webui 项目可以通过 webui 调用 API 进行自建的AI绘图，无需依赖于 novel ai API，对于一些拥有 GPU 服务器或其他可以本地运行的用户来说可以增添一种选择。
 如果您认为这项改动可以被接受，本人可以近期完成这项改动并提交相关的 PR。

**Comment by Alpaca4610** [comment]
> ref: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API stable diffusion webui 项目可以通过 webui 调用 API 进行自建的AI绘图，无需依赖于 novel ai API，对于一些拥有 GPU 服务器或其他可以本地运行的用户来说可以增添一种选择。 如果您认为这项改动可以被接受，本人可以近期完成这项改动并提交相关的 PR。

👌欢迎PR！
